dist: bionic
language: java
os: linux
jdk:
  - oraclejdk11

build:
  - cd src
  - javac com/richelbilderbeek/Main.java
  - java com.richelbilderbeek.Main

after_success:
  - bash <(curl-s https://codecov.io/bash

